workerPoolSpecs:
  machineSpec:
    machineType: n1-standard-4
    acceleratorType: NVIDIA_TESLA_T4
    acceleratorCount: 1
  replicaCount: 1
  executorImageUri: us-docker.pkg.dev/vertex-ai/training/pytorch-gpu.1-13.py310:latest
  pythonModule: trainer.task
args: --train-files=/gcs/wmap-811k/WM811K.pkl, --job-dir=wmap-811k/